/**
 * Generate Foundation Layer Tokens
 * 
 * This generator creates the foundation layer CSS files that contain
 * design system tokens as CSS custom properties.
 * 
 * Supports: USWDS (default), Material Design, Bootstrap
 * 
 * Architecture:
 *   Design System → Token Parser → Foundation Tokens → Semantic Tokens → Component Tokens
 * 
 * Usage:
 *   npm run generate:foundation           # Defaults to USWDS
 *   tsx src/lib/token-generators/generate-foundation-tokens.ts uswds
 *   tsx src/lib/token-generators/generate-foundation-tokens.ts material
 */

import { writeFileSync, mkdirSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';
import type { ParsedTokens } from './types.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

/**
 * Supported design systems
 */
export type DesignSystem = 'uswds' | 'material' | 'bootstrap';

/**
 * Load parser for the specified design system
 * 
 * @param designSystem - Design system to load parser for
 * @returns Parsed tokens in standardized format
 */
async function loadParser(designSystem: DesignSystem): Promise<ParsedTokens> {
  switch (designSystem) {
    case 'uswds': {
      const { parseUSWDSTokens } = await import('./parse-tokens/uswds/index.js');
      return parseUSWDSTokens();
    }
    
    case 'material':
      throw new Error(
        'Material Design token parser not yet implemented.\n\n' +
        'To add Material Design support:\n' +
        '  1. Create parse-tokens/material/index.ts\n' +
        '  2. Implement parseMaterialTokens() function\n' +
        '  3. Export parseMaterialTokens from the module\n\n' +
        'Then run: npm run parse:tokens material'
      );
    
    case 'bootstrap':
      throw new Error(
        'Bootstrap token parser not yet implemented.\n\n' +
        'To add Bootstrap support:\n' +
        '  1. Create parse-tokens/bootstrap/index.ts\n' +
        '  2. Implement parseBootstrapTokens() function\n' +
        '  3. Export parseBootstrapTokens from the module\n\n' +
        'Then run: npm run parse:tokens bootstrap'
      );
    
    default:
      throw new Error(`Unsupported design system: ${designSystem}`);
  }
}

/**
 * Generate color tokens CSS
 */
function generateColorCSS(tokens: ParsedTokens, designSystem: string): string {
  const designSystemUpper = designSystem.toUpperCase();
  const lines: string[] = [
    '/**',
    ` * ${designSystemUpper} Foundation Color Tokens`,
    ' * ',
    ` * System colors, theme colors, and state colors from ${designSystemUpper}`,
    ` * Generated from ${designSystemUpper} v${tokens.version}`,
    ' * ',
    ' * Do not edit this file directly. It is generated by:',
    ' * npm run generate:foundation',
    ' */',
    '',
    ':root {',
    '  /* ================================== */',
    '  /* System Colors                      */',
    '  /* ================================== */',
    ''
  ];

  // System colors
  Object.entries(tokens.colors.system).forEach(([name, token]) => {
    lines.push(`  --${name}: ${token.value};`);
  });

  lines.push('');
  lines.push('  /* ================================== */');
  lines.push('  /* Theme Colors                       */');
  lines.push('  /* ================================== */');
  lines.push('');

  // Theme colors
  Object.entries(tokens.colors.theme).forEach(([name, token]) => {
    const value = token.reference ? `var(--${token.value})` : token.value;
    lines.push(`  --${name}: ${value};`);
  });

  lines.push('');
  lines.push('  /* ================================== */');
  lines.push('  /* State Colors                       */');
  lines.push('  /* ================================== */');
  lines.push('');

  // State colors
  Object.entries(tokens.colors.state).forEach(([name, token]) => {
    const value = token.reference ? `var(--${token.value})` : token.value;
    lines.push(`  --${name}: ${value};`);
  });

  lines.push('}');
  lines.push('');

  return lines.join('\n');
}

/**
 * Generate spacing tokens CSS
 */
function generateSpacingCSS(tokens: ParsedTokens, designSystem: string): string {
  const designSystemUpper = designSystem.toUpperCase();
  const lines: string[] = [
    '/**',
    ` * ${designSystemUpper} Foundation Spacing Tokens`,
    ' * ',
    ` * Generated from ${designSystemUpper} v${tokens.version}`,
    ' * ',
    ' * Do not edit this file directly. It is generated by:',
    ' * npm run generate:foundation',
    ' */',
    '',
    ':root {',
    '  /* ================================== */',
    '  /* Spacing Units                      */',
    '  /* ================================== */',
    ''
  ];

  Object.entries(tokens.spacing).forEach(([name, token]) => {
    lines.push(`  --spacing-${name}: ${token.value};`);
  });

  lines.push('}');
  lines.push('');

  return lines.join('\n');
}

/**
 * Generate typesetting tokens CSS
 */
function generateTypesettingCSS(tokens: ParsedTokens, designSystem: string): string {
  const designSystemUpper = designSystem.toUpperCase();
  const lines: string[] = [
    '/**',
    ` * ${designSystemUpper} Foundation Typesetting Tokens`,
    ' * ',
    ' * Font families, sizes, weights, line heights, letter spacing, and measure',
    ` * Generated from ${designSystemUpper} v${tokens.version}`,
    ' * ',
    ' * Do not edit this file directly. It is generated by:',
    ' * npm run generate:foundation',
    ' */',
    '',
    ':root {',
    '  /* ================================== */',
    '  /* Font Families                      */',
    '  /* ================================== */',
    ''
  ];

  // Font families
  Object.entries(tokens.typography.family).forEach(([name, token]) => {
    const fontStack = Array.isArray(token.value) 
      ? token.value.map(f => f.includes(' ') ? `"${f}"` : f).join(', ')
      : token.value;
    lines.push(`  --font-${name}: ${fontStack};`);
  });

  lines.push('');
  lines.push('  /* ================================== */');
  lines.push('  /* Font Sizes                         */');
  lines.push('  /* ================================== */');
  lines.push('');

  // Font sizes
  Object.entries(tokens.typography.size).forEach(([name, token]) => {
    lines.push(`  --font-size-${name}: ${token.value};`);
  });

  lines.push('');
  lines.push('  /* ================================== */');
  lines.push('  /* Font Weights                       */');
  lines.push('  /* ================================== */');
  lines.push('');

  // Font weights
  Object.entries(tokens.typography.weight).forEach(([name, token]) => {
    lines.push(`  --font-weight-${name}: ${token.value};`);
  });

  lines.push('');
  lines.push('  /* ================================== */');
  lines.push('  /* Line Heights                       */');
  lines.push('  /* ================================== */');
  lines.push('');

  // Line heights
  Object.entries(tokens.typography.lineHeight).forEach(([name, token]) => {
    lines.push(`  --line-height-${name}: ${token.value};`);
  });

  lines.push('');
  lines.push('  /* ================================== */');
  lines.push('  /* Letter Spacing                     */');
  lines.push('  /* ================================== */');
  lines.push('');

  // Letter spacing
  Object.entries(tokens.typography.letterSpacing).forEach(([name, token]) => {
    lines.push(`  --letter-spacing-${name}: ${token.value};`);
  });

  lines.push('');
  lines.push('  /* ================================== */');
  lines.push('  /* Measure (Line Length)              */');
  lines.push('  /* ================================== */');
  lines.push('');

  // Measure
  Object.entries(tokens.typography.measure).forEach(([name, token]) => {
    lines.push(`  --measure-${name}: ${token.value};`);
  });

  lines.push('}');
  lines.push('');

  return lines.join('\n');
}

/**
 * Generate shadow tokens CSS
 */
function generateShadowCSS(tokens: ParsedTokens, designSystem: string): string {
  const designSystemUpper = designSystem.toUpperCase();
  const lines: string[] = [
    '/**',
    ` * ${designSystemUpper} Foundation Shadow Tokens`,
    ' * ',
    ` * Generated from ${designSystemUpper} v${tokens.version}`,
    ' * ',
    ' * Do not edit this file directly. It is generated by:',
    ' * npm run generate:foundation',
    ' */',
    '',
    ':root {',
    '  /* ================================== */',
    '  /* Shadows                            */',
    '  /* ================================== */',
    ''
  ];

  Object.entries(tokens.shadow).forEach(([name, token]) => {
    lines.push(`  --shadow-${name}: ${token.value};`);
  });

  lines.push('}');
  lines.push('');

  return lines.join('\n');
}

/**
 * Generate opacity tokens CSS
 */
function generateOpacityCSS(tokens: ParsedTokens, designSystem: string): string {
  const designSystemUpper = designSystem.toUpperCase();
  const lines: string[] = [
    '/**',
    ` * ${designSystemUpper} Foundation Opacity Tokens`,
    ' * ',
    ` * Generated from ${designSystemUpper} v${tokens.version}`,
    ' * ',
    ' * Do not edit this file directly. It is generated by:',
    ' * npm run generate:foundation',
    ' */',
    '',
    ':root {',
    '  /* ================================== */',
    '  /* Opacity                            */',
    '  /* ================================== */',
    ''
  ];

  Object.entries(tokens.opacity).forEach(([name, token]) => {
    lines.push(`  --opacity-${name}: ${token.value};`);
  });

  lines.push('}');
  lines.push('');

  return lines.join('\n');
}

/**
 * Generate z-index tokens CSS
 */
function generateZIndexCSS(tokens: ParsedTokens, designSystem: string): string {
  const designSystemUpper = designSystem.toUpperCase();
  const lines: string[] = [
    '/**',
    ` * ${designSystemUpper} Foundation Z-Index Tokens`,
    ' * ',
    ` * Generated from ${designSystemUpper} v${tokens.version}`,
    ' * ',
    ' * Do not edit this file directly. It is generated by:',
    ' * npm run generate:foundation',
    ' */',
    '',
    ':root {',
    '  /* ================================== */',
    '  /* Z-Index                            */',
    '  /* ================================== */',
    ''
  ];

  Object.entries(tokens.zIndex).forEach(([name, token]) => {
    lines.push(`  --z-index-${name}: ${token.value};`);
  });

  lines.push('}');
  lines.push('');

  return lines.join('\n');
}

/**
 * Generate flex tokens CSS
 */
function generateFlexCSS(tokens: ParsedTokens, designSystem: string): string {
  const designSystemUpper = designSystem.toUpperCase();
  const lines: string[] = [
    '/**',
    ` * ${designSystemUpper} Foundation Flex Tokens`,
    ' * ',
    ` * Generated from ${designSystemUpper} v${tokens.version}`,
    ' * ',
    ' * Do not edit this file directly. It is generated by:',
    ' * npm run generate:foundation',
    ' */',
    '',
    ':root {',
    '  /* ================================== */',
    '  /* Flex                               */',
    '  /* ================================== */',
    ''
  ];

  Object.entries(tokens.flex).forEach(([name, token]) => {
    lines.push(`  --flex-${name}: ${token.value};`);
  });

  lines.push('}');
  lines.push('');

  return lines.join('\n');
}

/**
 * Generate order tokens CSS
 */
function generateOrderCSS(tokens: ParsedTokens, designSystem: string): string {
  const designSystemUpper = designSystem.toUpperCase();
  const lines: string[] = [
    '/**',
    ` * ${designSystemUpper} Foundation Order Tokens`,
    ' * ',
    ` * Generated from ${designSystemUpper} v${tokens.version}`,
    ' * ',
    ' * Do not edit this file directly. It is generated by:',
    ' * npm run generate:foundation',
    ' */',
    '',
    ':root {',
    '  /* ================================== */',
    '  /* Order                              */',
    '  /* ================================== */',
    ''
  ];

  Object.entries(tokens.order).forEach(([name, token]) => {
    lines.push(`  --order-${name}: ${token.value};`);
  });

  lines.push('}');
  lines.push('');

  return lines.join('\n');
}


/**
 * Generate all.css convenience import
 */
function generateAllCSS(tokens: ParsedTokens, designSystem: string): string {
  const designSystemUpper = designSystem.toUpperCase();
  return [
    '/**',
    ` * ${designSystemUpper} Foundation Tokens - All`,
    ' * ',
    ` * Convenience import for all ${designSystemUpper} foundation tokens`,
    ` * Generated from ${designSystemUpper} v${tokens.version}`,
    ' * ',
    ' * Usage:',
    ` *   @import 'svelte-ui/tokens/foundation/${designSystem}/all.css';`,
    ' */',
    '',
    '@import \'./color.css\';',
    '@import \'./spacing.css\';',
    '@import \'./typesetting.css\';',
    '@import \'./shadow.css\';',
    '@import \'./opacity.css\';',
    '@import \'./z-index.css\';',
    '@import \'./flex.css\';',
    '@import \'./order.css\';',
    ''
  ].join('\n');
}

/**
 * Main generator function
 */
export async function generateFoundationTokens(designSystem: DesignSystem = 'uswds') {
  const designSystemUpper = designSystem.toUpperCase();
  console.log(`=== ${designSystemUpper} Foundation Token Generator ===\n`);

  // Parse tokens via dynamic import
  console.log(`Parsing ${designSystemUpper} tokens...`);
  const tokens = await loadParser(designSystem);
  console.log(`  Parsed ${Object.keys(tokens.colors.system).length + Object.keys(tokens.colors.theme).length + Object.keys(tokens.colors.state).length} color tokens`);

  // Create output directory
  const OUTPUT_DIR = resolve(__dirname, `../../tokens/foundation/${designSystem}`);
  mkdirSync(OUTPUT_DIR, { recursive: true });
  console.log(`\nOutput directory: ${OUTPUT_DIR}`);

  // Generate token CSS files
  console.log('\nGenerating token CSS files...');

  const files = [
    { name: 'color.css', content: generateColorCSS(tokens, designSystem) },
    { name: 'spacing.css', content: generateSpacingCSS(tokens, designSystem) },
    { name: 'typesetting.css', content: generateTypesettingCSS(tokens, designSystem) },
    { name: 'shadow.css', content: generateShadowCSS(tokens, designSystem) },
    { name: 'opacity.css', content: generateOpacityCSS(tokens, designSystem) },
    { name: 'z-index.css', content: generateZIndexCSS(tokens, designSystem) },
    { name: 'flex.css', content: generateFlexCSS(tokens, designSystem) },
    { name: 'order.css', content: generateOrderCSS(tokens, designSystem) },
    { name: 'all.css', content: generateAllCSS(tokens, designSystem) }
  ];

  files.forEach(file => {
    const filePath = resolve(OUTPUT_DIR, file.name);
    writeFileSync(filePath, file.content, 'utf-8');
    console.log(`  ✅ ${file.name}`);
  });

  console.log(`\n✅ ${designSystemUpper} Foundation token generation complete!`);
}

// Run if called directly
if (import.meta.url === `file://${process.argv[1]}`) {
  const designSystemArg = process.argv[2] as DesignSystem | undefined;
  
  // Validate design system argument
  const validSystems: DesignSystem[] = ['uswds', 'material', 'bootstrap'];
  
  if (designSystemArg && !validSystems.includes(designSystemArg)) {
    console.error(`\n❌ Error: Invalid design system "${designSystemArg}"\n`);
    console.error('Valid options: uswds, material, bootstrap\n');
    console.error('Usage:');
    console.error('  npm run generate:foundation           # Defaults to uswds');
    console.error('  npm run generate:foundation uswds');
    console.error('  npm run generate:foundation material');
    console.error('  npm run generate:foundation bootstrap\n');
    process.exit(1);
  }
  
  const designSystem = designSystemArg || 'uswds';
  
  generateFoundationTokens(designSystem).catch(error => {
    console.error('\n❌ Error generating foundation tokens:', error.message);
    process.exit(1);
  });
}
