/**
 * Generate CSS custom property files from parsed USWDS tokens
 * 
 * This generator creates the foundation layer CSS files that contain
 * all USWDS design tokens as CSS custom properties.
 * 
 * Architecture:
 *   USWDS Package → Token Parser → Foundation CSS → Semantic CSS → Components
 * 
 * Usage:
 *   npm run generate:css
 *   tsx src/lib/token-generators/generate-css-tokens.ts
 */

import { writeFileSync, mkdirSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';
import { parseUSWDSTokens } from './parse-tokens/uswds/index.js';
import type { ParsedTokens } from './types.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const OUTPUT_DIR = resolve(__dirname, '../../tokens/foundation/uswds');

/**
 * Generate color tokens CSS
 */
function generateColorCSS(tokens: ParsedTokens): string {
  const lines: string[] = [
    '/**',
    ' * USWDS Foundation Color Tokens',
    ' * ',
    ' * System colors, theme colors, and state colors from USWDS',
    ` * Generated from USWDS v${tokens.version}`,
    ' * ',
    ' * Do not edit this file directly. It is generated by:',
    ' * npm run generate:css',
    ' */',
    '',
    ':root {',
    '  /* ================================== */',
    '  /* System Colors                      */',
    '  /* ================================== */',
    ''
  ];

  // System colors
  Object.entries(tokens.colors.system).forEach(([name, token]) => {
    lines.push(`  --${name}: ${token.value};`);
  });

  lines.push('');
  lines.push('  /* ================================== */');
  lines.push('  /* Theme Colors                       */');
  lines.push('  /* ================================== */');
  lines.push('');

  // Theme colors
  Object.entries(tokens.colors.theme).forEach(([name, token]) => {
    const value = token.reference ? `var(--${token.value})` : token.value;
    lines.push(`  --${name}: ${value};`);
  });

  lines.push('');
  lines.push('  /* ================================== */');
  lines.push('  /* State Colors                       */');
  lines.push('  /* ================================== */');
  lines.push('');

  // State colors
  Object.entries(tokens.colors.state).forEach(([name, token]) => {
    const value = token.reference ? `var(--${token.value})` : token.value;
    lines.push(`  --${name}: ${value};`);
  });

  lines.push('}');
  lines.push('');

  return lines.join('\n');
}

/**
 * Generate spacing tokens CSS
 */
function generateSpacingCSS(tokens: ParsedTokens): string {
  const lines: string[] = [
    '/**',
    ' * USWDS Foundation Spacing Tokens',
    ' * ',
    ` * Generated from USWDS v${tokens.version}`,
    ' * ',
    ' * Do not edit this file directly. It is generated by:',
    ' * npm run generate:css',
    ' */',
    '',
    ':root {',
    '  /* ================================== */',
    '  /* Spacing Units                      */',
    '  /* ================================== */',
    ''
  ];

  Object.entries(tokens.spacing).forEach(([name, token]) => {
    lines.push(`  --spacing-${name}: ${token.value};`);
  });

  lines.push('}');
  lines.push('');

  return lines.join('\n');
}

/**
 * Generate typesetting tokens CSS
 */
function generateTypesettingCSS(tokens: ParsedTokens): string {
  const lines: string[] = [
    '/**',
    ' * USWDS Foundation Typesetting Tokens',
    ' * ',
    ' * Font families, sizes, weights, line heights, letter spacing, and measure',
    ` * Generated from USWDS v${tokens.version}`,
    ' * ',
    ' * Do not edit this file directly. It is generated by:',
    ' * npm run generate:css',
    ' */',
    '',
    ':root {',
    '  /* ================================== */',
    '  /* Font Families                      */',
    '  /* ================================== */',
    ''
  ];

  // Font families
  Object.entries(tokens.typography.family).forEach(([name, token]) => {
    const fontStack = Array.isArray(token.value) 
      ? token.value.map(f => f.includes(' ') ? `"${f}"` : f).join(', ')
      : token.value;
    lines.push(`  --font-${name}: ${fontStack};`);
  });

  lines.push('');
  lines.push('  /* ================================== */');
  lines.push('  /* Font Sizes                         */');
  lines.push('  /* ================================== */');
  lines.push('');

  // Font sizes
  Object.entries(tokens.typography.size).forEach(([name, token]) => {
    lines.push(`  --font-size-${name}: ${token.value};`);
  });

  lines.push('');
  lines.push('  /* ================================== */');
  lines.push('  /* Font Weights                       */');
  lines.push('  /* ================================== */');
  lines.push('');

  // Font weights
  Object.entries(tokens.typography.weight).forEach(([name, token]) => {
    lines.push(`  --font-weight-${name}: ${token.value};`);
  });

  lines.push('');
  lines.push('  /* ================================== */');
  lines.push('  /* Line Heights                       */');
  lines.push('  /* ================================== */');
  lines.push('');

  // Line heights
  Object.entries(tokens.typography.lineHeight).forEach(([name, token]) => {
    lines.push(`  --line-height-${name}: ${token.value};`);
  });

  lines.push('');
  lines.push('  /* ================================== */');
  lines.push('  /* Letter Spacing                     */');
  lines.push('  /* ================================== */');
  lines.push('');

  // Letter spacing
  Object.entries(tokens.typography.letterSpacing).forEach(([name, token]) => {
    lines.push(`  --letter-spacing-${name}: ${token.value};`);
  });

  lines.push('');
  lines.push('  /* ================================== */');
  lines.push('  /* Measure (Line Length)              */');
  lines.push('  /* ================================== */');
  lines.push('');

  // Measure
  Object.entries(tokens.typography.measure).forEach(([name, token]) => {
    lines.push(`  --measure-${name}: ${token.value};`);
  });

  lines.push('}');
  lines.push('');

  return lines.join('\n');
}

/**
 * Generate shadow tokens CSS
 */
function generateShadowCSS(tokens: ParsedTokens): string {
  const lines: string[] = [
    '/**',
    ' * USWDS Foundation Shadow Tokens',
    ' * ',
    ` * Generated from USWDS v${tokens.version}`,
    ' * ',
    ' * Do not edit this file directly. It is generated by:',
    ' * npm run generate:css',
    ' */',
    '',
    ':root {',
    '  /* ================================== */',
    '  /* Shadows                            */',
    '  /* ================================== */',
    ''
  ];

  Object.entries(tokens.shadow).forEach(([name, token]) => {
    lines.push(`  --shadow-${name}: ${token.value};`);
  });

  lines.push('}');
  lines.push('');

  return lines.join('\n');
}

/**
 * Generate opacity tokens CSS
 */
function generateOpacityCSS(tokens: ParsedTokens): string {
  const lines: string[] = [
    '/**',
    ' * USWDS Foundation Opacity Tokens',
    ' * ',
    ` * Generated from USWDS v${tokens.version}`,
    ' * ',
    ' * Do not edit this file directly. It is generated by:',
    ' * npm run generate:css',
    ' */',
    '',
    ':root {',
    '  /* ================================== */',
    '  /* Opacity                            */',
    '  /* ================================== */',
    ''
  ];

  Object.entries(tokens.opacity).forEach(([name, token]) => {
    lines.push(`  --opacity-${name}: ${token.value};`);
  });

  lines.push('}');
  lines.push('');

  return lines.join('\n');
}

/**
 * Generate z-index tokens CSS
 */
function generateZIndexCSS(tokens: ParsedTokens): string {
  const lines: string[] = [
    '/**',
    ' * USWDS Foundation Z-Index Tokens',
    ' * ',
    ` * Generated from USWDS v${tokens.version}`,
    ' * ',
    ' * Do not edit this file directly. It is generated by:',
    ' * npm run generate:css',
    ' */',
    '',
    ':root {',
    '  /* ================================== */',
    '  /* Z-Index                            */',
    '  /* ================================== */',
    ''
  ];

  Object.entries(tokens.zIndex).forEach(([name, token]) => {
    lines.push(`  --z-index-${name}: ${token.value};`);
  });

  lines.push('}');
  lines.push('');

  return lines.join('\n');
}

/**
 * Generate flex tokens CSS
 */
function generateFlexCSS(tokens: ParsedTokens): string {
  const lines: string[] = [
    '/**',
    ' * USWDS Foundation Flex Tokens',
    ' * ',
    ` * Generated from USWDS v${tokens.version}`,
    ' * ',
    ' * Do not edit this file directly. It is generated by:',
    ' * npm run generate:css',
    ' */',
    '',
    ':root {',
    '  /* ================================== */',
    '  /* Flex                               */',
    '  /* ================================== */',
    ''
  ];

  Object.entries(tokens.flex).forEach(([name, token]) => {
    lines.push(`  --flex-${name}: ${token.value};`);
  });

  lines.push('}');
  lines.push('');

  return lines.join('\n');
}

/**
 * Generate order tokens CSS
 */
function generateOrderCSS(tokens: ParsedTokens): string {
  const lines: string[] = [
    '/**',
    ' * USWDS Foundation Order Tokens',
    ' * ',
    ` * Generated from USWDS v${tokens.version}`,
    ' * ',
    ' * Do not edit this file directly. It is generated by:',
    ' * npm run generate:css',
    ' */',
    '',
    ':root {',
    '  /* ================================== */',
    '  /* Order                              */',
    '  /* ================================== */',
    ''
  ];

  Object.entries(tokens.order).forEach(([name, token]) => {
    lines.push(`  --order-${name}: ${token.value};`);
  });

  lines.push('}');
  lines.push('');

  return lines.join('\n');
}


/**
 * Generate all.css convenience import
 */
function generateAllCSS(tokens: ParsedTokens): string {
  return [
    '/**',
    ' * USWDS Foundation Tokens - All',
    ' * ',
    ' * Convenience import for all USWDS foundation tokens',
    ` * Generated from USWDS v${tokens.version}`,
    ' * ',
    ' * Usage:',
    " *   @import 'svelte-ui/tokens/foundation/uswds/all.css';",
    ' */',
    '',
    '@import \'./color.css\';',
    '@import \'./spacing.css\';',
    '@import \'./typesetting.css\';',
    '@import \'./shadow.css\';',
    '@import \'./opacity.css\';',
    '@import \'./z-index.css\';',
    '@import \'./flex.css\';',
    '@import \'./order.css\';',
    ''
  ].join('\n');
}

/**
 * Main generator function
 */
export function generateFoundationCSS() {
  console.log('=== USWDS Foundation CSS Generator ===\n');

  // Parse tokens
  console.log('Parsing USWDS tokens...');
  const tokens = parseUSWDSTokens();
  console.log(`  Parsed ${Object.keys(tokens.colors.system).length + Object.keys(tokens.colors.theme).length + Object.keys(tokens.colors.state).length} color tokens`);

  // Create output directory
  mkdirSync(OUTPUT_DIR, { recursive: true });
  console.log(`\nOutput directory: ${OUTPUT_DIR}`);

  // Generate CSS files
  console.log('\nGenerating CSS files...');

  const files = [
    { name: 'color.css', content: generateColorCSS(tokens) },
    { name: 'spacing.css', content: generateSpacingCSS(tokens) },
    { name: 'typesetting.css', content: generateTypesettingCSS(tokens) },
    { name: 'shadow.css', content: generateShadowCSS(tokens) },
    { name: 'opacity.css', content: generateOpacityCSS(tokens) },
    { name: 'z-index.css', content: generateZIndexCSS(tokens) },
    { name: 'flex.css', content: generateFlexCSS(tokens) },
    { name: 'order.css', content: generateOrderCSS(tokens) },
    { name: 'all.css', content: generateAllCSS(tokens) }
  ];

  files.forEach(file => {
    const filePath = resolve(OUTPUT_DIR, file.name);
    writeFileSync(filePath, file.content, 'utf-8');
    console.log(`  ✅ ${file.name}`);
  });

  console.log('\n✅ Foundation CSS generation complete!');
}

// Run if called directly
if (import.meta.url === `file://${process.argv[1]}`) {
  generateFoundationCSS();
}
