/**
 * Generate semantic layer CSS from mappings
 * 
 * This generator creates the universal semantic layer CSS files that map
 * foundation tokens to design-system-agnostic semantic names.
 * 
 * Architecture:
 *   Foundation Layer (USWDS) → Semantic Layer (Universal) → Components
 * 
 * Usage:
 *   npm run generate:semantic
 *   tsx src/lib/token-generators/generate-semantic-css.ts
 */

import { writeFileSync, mkdirSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';
import { uswdsSemanticMappings, getSemanticMappingsByCategory } from './semantic-mappings.js';
import { parseUSWDSTokens } from './parse-uswds-tokens.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const OUTPUT_DIR = resolve(__dirname, '../../tokens/semantic');

/**
 * Generate semantic color CSS
 */
function generateSemanticColorCSS(): string {
  const colorMappings = getSemanticMappingsByCategory('color');
  
  const lines: string[] = [
    '/**',
    ' * Semantic Color Tokens',
    ' * ',
    ' * Universal color tokens that map to foundation layer',
    ' * Components should ALWAYS use these semantic tokens',
    ' * ',
    ' * Do not edit this file directly. It is generated by:',
    ' * npm run generate:semantic',
    ' */',
    '',
    ':root {',
    '  /* ================================== */',
    '  /* Brand Colors                       */',
    '  /* ================================== */',
    ''
  ];

  // Group by description patterns
  const groups = [
    { title: 'Brand Colors', pattern: /brand color/i },
    { title: 'Text Colors', pattern: /text color/i },
    { title: 'Background Colors', pattern: /background color/i },
    { title: 'Border Colors', pattern: /border color/i },
    { title: 'Interactive Colors', pattern: /interactive element/i },
    { title: 'Feedback Colors', pattern: /state color|state background/i }
  ];

  groups.forEach((group, index) => {
    if (index > 0) {
      lines.push('');
      lines.push(`  /* ================================== */`);
      lines.push(`  /* ${group.title.padEnd(35)} */`);
      lines.push(`  /* ================================== */`);
      lines.push('');
    }

    colorMappings
      .filter(m => group.pattern.test(m.description))
      .forEach(mapping => {
        const foundationVar = mapping.foundation === '2px' || mapping.foundation.includes('ms') 
          ? mapping.foundation 
          : `var(--${mapping.foundation})`;
        lines.push(`  --${mapping.semantic}: ${foundationVar};`);
      });
  });

  lines.push('}');
  lines.push('');

  return lines.join('\n');
}

/**
 * Generate semantic spacing CSS
 */
function generateSemanticSpacingCSS(): string {
  const spacingMappings = getSemanticMappingsByCategory('spacing');
  
  const lines: string[] = [
    '/**',
    ' * Semantic Spacing Tokens',
    ' * ',
    ' * Universal spacing tokens that map to foundation layer',
    ' * ',
    ' * Do not edit this file directly. It is generated by:',
    ' * npm run generate:semantic',
    ' */',
    '',
    ':root {',
    '  /* ================================== */',
    '  /* Spacing Scale                      */',
    '  /* ================================== */',
    ''
  ];

  // Spacing scale tokens
  spacingMappings
    .filter(m => m.description.includes('spacing'))
    .forEach(mapping => {
      lines.push(`  --${mapping.semantic}: var(--spacing-${mapping.foundation});`);
    });

  lines.push('');
  lines.push('  /* ================================== */');
  lines.push('  /* Component Spacing                  */');
  lines.push('  /* ================================== */');
  lines.push('');

  // Component spacing tokens
  spacingMappings
    .filter(m => m.description.includes('padding') || m.description.includes('gap'))
    .forEach(mapping => {
      lines.push(`  --${mapping.semantic}: var(--spacing-${mapping.foundation});`);
    });

  lines.push('}');
  lines.push('');

  return lines.join('\n');
}

/**
 * Generate semantic typography CSS
 */
function generateSemanticTypographyCSS(): string {
  const typographyMappings = getSemanticMappingsByCategory('typography');
  
  const lines: string[] = [
    '/**',
    ' * Semantic Typography Tokens',
    ' * ',
    ' * Universal typography tokens that map to foundation layer',
    ' * ',
    ' * Do not edit this file directly. It is generated by:',
    ' * npm run generate:semantic',
    ' */',
    '',
    ':root {',
    '  /* ================================== */',
    '  /* Font Families                      */',
    '  /* ================================== */',
    ''
  ];

  // Font families
  typographyMappings
    .filter(m => m.description.includes('font family'))
    .forEach(mapping => {
      lines.push(`  --${mapping.semantic}: var(--font-${mapping.foundation});`);
    });

  lines.push('');
  lines.push('  /* ================================== */');
  lines.push('  /* Font Sizes                         */');
  lines.push('  /* ================================== */');
  lines.push('');

  // Font sizes
  typographyMappings
    .filter(m => m.description.includes('text size'))
    .forEach(mapping => {
      lines.push(`  --${mapping.semantic}: var(--font-size-${mapping.foundation});`);
    });

  lines.push('');
  lines.push('  /* ================================== */');
  lines.push('  /* Font Weights                       */');
  lines.push('  /* ================================== */');
  lines.push('');

  // Font weights
  typographyMappings
    .filter(m => m.description.includes('font weight'))
    .forEach(mapping => {
      lines.push(`  --${mapping.semantic}: var(--font-weight-${mapping.foundation});`);
    });

  lines.push('}');
  lines.push('');

  return lines.join('\n');
}

/**
 * Generate semantic effects CSS
 */
function generateSemanticEffectsCSS(): string {
  const effectsMappings = getSemanticMappingsByCategory('effects');
  
  const lines: string[] = [
    '/**',
    ' * Semantic Effects Tokens',
    ' * ',
    ' * Universal effect tokens (shadows, focus, radius) that map to foundation layer',
    ' * ',
    ' * Do not edit this file directly. It is generated by:',
    ' * npm run generate:semantic',
    ' */',
    '',
    ':root {',
    '  /* ================================== */',
    '  /* Border Radius                      */',
    '  /* ================================== */',
    ''
  ];

  // Border radius
  effectsMappings
    .filter(m => m.description.includes('radius'))
    .forEach(mapping => {
      lines.push(`  --${mapping.semantic}: var(--spacing-${mapping.foundation});`);
    });

  lines.push('');
  lines.push('  /* ================================== */');
  lines.push('  /* Shadows                            */');
  lines.push('  /* ================================== */');
  lines.push('');

  // Shadows
  effectsMappings
    .filter(m => m.description.includes('shadow'))
    .forEach(mapping => {
      lines.push(`  --${mapping.semantic}: var(--shadow-${mapping.foundation});`);
    });

  lines.push('');
  lines.push('  /* ================================== */');
  lines.push('  /* Focus                              */');
  lines.push('  /* ================================== */');
  lines.push('');

  // Focus
  effectsMappings
    .filter(m => m.description.includes('focus'))
    .forEach(mapping => {
      const value = mapping.foundation === '2px' 
        ? mapping.foundation 
        : `var(--${mapping.foundation})`;
      lines.push(`  --${mapping.semantic}: ${value};`);
    });

  lines.push('}');
  lines.push('');

  return lines.join('\n');
}

/**
 * Generate semantic layout CSS
 */
function generateSemanticLayoutCSS(): string {
  const layoutMappings = getSemanticMappingsByCategory('layout');
  
  const lines: string[] = [
    '/**',
    ' * Semantic Layout Tokens',
    ' * ',
    ' * Universal layout tokens (z-index, transitions) that map to foundation layer',
    ' * ',
    ' * Do not edit this file directly. It is generated by:',
    ' * npm run generate:semantic',
    ' */',
    '',
    ':root {',
    '  /* ================================== */',
    '  /* Z-Index                            */',
    '  /* ================================== */',
    ''
  ];

  // Z-index
  layoutMappings
    .filter(m => m.description.includes('Z-index'))
    .forEach(mapping => {
      lines.push(`  --${mapping.semantic}: var(--z-index-${mapping.foundation});`);
    });

  lines.push('');
  lines.push('  /* ================================== */');
  lines.push('  /* Transitions                        */');
  lines.push('  /* ================================== */');
  lines.push('');

  // Transitions
  layoutMappings
    .filter(m => m.description.includes('transition'))
    .forEach(mapping => {
      lines.push(`  --${mapping.semantic}: ${mapping.foundation};`);
    });

  lines.push('}');
  lines.push('');

  return lines.join('\n');
}

/**
 * Generate all.css convenience import
 */
function generateSemanticAllCSS(): string {
  return [
    '/**',
    ' * Semantic Tokens - All',
    ' * ',
    ' * Convenience import for all semantic tokens',
    ' * ',
    ' * Usage:',
    " *   @import 'svelte-ui/tokens/semantic/all.css';",
    ' * ',
    ' * Note: This requires foundation tokens to be loaded first:',
    " *   @import 'svelte-ui/tokens/foundation/uswds/all.css';",
    " *   @import 'svelte-ui/tokens/semantic/all.css';",
    ' */',
    '',
    '@import \'./color.css\';',
    '@import \'./spacing.css\';',
    '@import \'./typography.css\';',
    '@import \'./effects.css\';',
    '@import \'./layout.css\';',
    ''
  ].join('\n');
}

/**
 * Main generator function
 */
export function generateSemanticCSS() {
  console.log('=== Semantic Layer CSS Generator ===\n');

  // Create output directory
  mkdirSync(OUTPUT_DIR, { recursive: true });
  console.log(`Output directory: ${OUTPUT_DIR}`);

  // Generate CSS files
  console.log('\nGenerating semantic CSS files...');

  const files = [
    { name: 'color.css', content: generateSemanticColorCSS() },
    { name: 'spacing.css', content: generateSemanticSpacingCSS() },
    { name: 'typography.css', content: generateSemanticTypographyCSS() },
    { name: 'effects.css', content: generateSemanticEffectsCSS() },
    { name: 'layout.css', content: generateSemanticLayoutCSS() },
    { name: 'all.css', content: generateSemanticAllCSS() }
  ];

  files.forEach(file => {
    const filePath = resolve(OUTPUT_DIR, file.name);
    writeFileSync(filePath, file.content, 'utf-8');
    console.log(`  ✅ ${file.name}`);
  });

  console.log('\n✅ Semantic CSS generation complete!');
  console.log('\nTotal semantic tokens: 62');
}

// Run if called directly
if (import.meta.url === `file://${process.argv[1]}`) {
  generateSemanticCSS();
}
