/**
 * Component Token CSS Generator
 * 
 * Generates CSS custom properties for component-specific tokens.
 * Component tokens reference semantic tokens, creating a three-layer hierarchy:
 * 
 * Foundation → Semantic → Component
 * 
 * @module generate-component-tokens
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { allComponentTokens } from './component-mappings/index.js';
import type { ComponentTokens, ComponentTokenDefinition } from './types.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

/**
 * Output directory for component token CSS files
 */
const OUTPUT_DIR = path.join(__dirname, '../../tokens/components');

/**
 * Group component tokens by category
 */
function groupTokensByCategory(tokens: ComponentTokenDefinition[]): Map<string, ComponentTokenDefinition[]> {
  const groups = new Map<string, ComponentTokenDefinition[]>();
  
  for (const token of tokens) {
    const category = token.category;
    if (!groups.has(category)) {
      groups.set(category, []);
    }
    groups.get(category)!.push(token);
  }
  
  return groups;
}

/**
 * Generate CSS for a single component
 */
function generateComponentCSS(componentTokens: ComponentTokens): string {
  const { component, tokens } = componentTokens;
  const groups = groupTokensByCategory(tokens);
  
  // Sort categories in logical order
  const categoryOrder = ['color', 'spacing', 'typography', 'effects', 'layout'];
  const sortedCategories = Array.from(groups.keys()).sort((a, b) => {
    return categoryOrder.indexOf(a) - categoryOrder.indexOf(b);
  });
  
  const lines: string[] = [];
  
  // Header
  lines.push(`/**`);
  lines.push(` * ${component.charAt(0).toUpperCase() + component.slice(1)} Component Tokens`);
  lines.push(` *`);
  lines.push(` * Component-specific design tokens that reference semantic tokens.`);
  lines.push(` * Override these to customize the ${component} component.`);
  lines.push(` *`);
  lines.push(` * Layer: Component (references Semantic)`);
  lines.push(` *`);
  lines.push(` * Generated by: src/lib/token-generators/generate-component-tokens.ts`);
  lines.push(` * Source mappings: src/lib/token-generators/component-mappings/${component}-tokens.ts`);
  lines.push(` *`);
  lines.push(` * To customize: Edit the source mapping file and run 'npm run generate:components'`);
  lines.push(` */`);
  lines.push('');
  lines.push(':root {');
  
  // Generate tokens by category
  for (const category of sortedCategories) {
    const categoryTokens = groups.get(category)!;
    const categoryTitle = category.charAt(0).toUpperCase() + category.slice(1);
    
    lines.push(`  /* ================================== */`);
    lines.push(`  /* ${categoryTitle} */`);
    lines.push(`  /* ================================== */`);
    lines.push('');
    
    for (const token of categoryTokens) {
      // Add description as comment
      lines.push(`  /* ${token.description} */`);
      
      // Generate CSS custom property
      lines.push(`  --${token.token}: var(--${token.semantic});`);
      lines.push('');
    }
  }
  
  lines.push('}');
  
  return lines.join('\n');
}

/**
 * Generate all.css that imports all component token files
 */
function generateAllCSS(components: string[]): string {
  const lines: string[] = [];
  
  lines.push(`/**`);
  lines.push(` * All Component Tokens`);
  lines.push(` *`);
  lines.push(` * Imports all component-specific design tokens.`);
  lines.push(` *`);
  lines.push(` * Usage:`);
  lines.push(` *   @import 'svelte-ui/tokens/components/all.css';`);
  lines.push(` *`);
  lines.push(` * Or import individual components:`);
  lines.push(` *   @import 'svelte-ui/tokens/components/button.css';`);
  lines.push(` *`);
  lines.push(` * Generated by: src/lib/token-generators/generate-component-tokens.ts`);
  lines.push(` */`);
  lines.push('');
  
  for (const component of components.sort()) {
    lines.push(`@import './${component}.css';`);
  }
  
  return lines.join('\n');
}

/**
 * Main generation function
 */
function generateComponentTokens(): void {
  console.log('🎨 Generating component token CSS files...\n');
  
  // Create output directory
  if (!fs.existsSync(OUTPUT_DIR)) {
    fs.mkdirSync(OUTPUT_DIR, { recursive: true });
    console.log(`✓ Created directory: ${OUTPUT_DIR}`);
  }
  
  const componentNames: string[] = [];
  let totalTokens = 0;
  
  // Generate CSS for each component
  for (const componentTokens of allComponentTokens) {
    const { component, tokens } = componentTokens;
    const css = generateComponentCSS(componentTokens);
    const filename = `${component}.css`;
    const filepath = path.join(OUTPUT_DIR, filename);
    
    fs.writeFileSync(filepath, css, 'utf-8');
    
    componentNames.push(component);
    totalTokens += tokens.length;
    
    console.log(`✓ Generated ${filename} (${tokens.length} tokens)`);
  }
  
  // Generate all.css
  const allCSS = generateAllCSS(componentNames);
  const allFilepath = path.join(OUTPUT_DIR, 'all.css');
  fs.writeFileSync(allFilepath, allCSS, 'utf-8');
  console.log(`✓ Generated all.css (imports ${componentNames.length} components)`);
  
  console.log('\n📊 Component Token Summary:');
  console.log(`   Components: ${componentNames.length}`);
  console.log(`   Total Tokens: ${totalTokens}`);
  console.log(`   Output: ${OUTPUT_DIR}`);
}

// Run generator
generateComponentTokens();
