/**
 * Generate semantic layer CSS from mappings
 * 
 * This generator creates the universal semantic layer CSS files that map
 * foundation tokens to design-system-agnostic semantic names.
 * 
 * File structure matches USWDS design token categories:
 *   - color.css
 *   - spacing.css
 *   - typesetting.css
 *   - shadow.css
 *   - opacity.css
 *   - z-index.css
 *   - flex.css
 *   - order.css
 * 
 * Architecture:
 *   Foundation Layer (USWDS) → Semantic Layer (Universal) → Components
 * 
 * Usage:
 *   npm run generate:semantic
 *   tsx src/lib/token-generators/generate-semantic-css.ts
 */

import { writeFileSync, mkdirSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';
import { uswdsSemanticMappings, getSemanticMappingsByCategory } from './semantic-mappings.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const OUTPUT_DIR = resolve(__dirname, '../../tokens/semantic');

/**
 * Generate semantic color CSS
 */
function generateSemanticColorCSS(): string {
  const colorMappings = getSemanticMappingsByCategory('color');
  
  const lines: string[] = [
    '/**',
    ' * Semantic Color Tokens',
    ' * ',
    ' * Universal color tokens that map to foundation layer',
    ' * Components should ALWAYS use these semantic tokens',
    ' * ',
    ' * Do not edit this file directly. It is generated by:',
    ' * npm run generate:semantic',
    ' */',
    '',
    ':root {',
    '  /* ================================== */',
    '  /* Brand Colors                       */',
    '  /* ================================== */',
    ''
  ];

  // Group by description patterns
  const groups = [
    { title: 'Brand Colors', pattern: /brand color/i },
    { title: 'Text Colors', pattern: /text color/i },
    { title: 'Background Colors', pattern: /background color/i },
    { title: 'Border Colors', pattern: /border color/i },
    { title: 'Interactive Colors', pattern: /interactive element/i },
    { title: 'Feedback Colors', pattern: /state color|state background/i },
    { title: 'Focus Color', pattern: /focus outline/i }
  ];

  groups.forEach((group, index) => {
    if (index > 0) {
      lines.push('');
      lines.push(`  /* ================================== */`);
      lines.push(`  /* ${group.title.padEnd(35)} */`);
      lines.push(`  /* ================================== */`);
      lines.push('');
    }

    colorMappings
      .filter(m => group.pattern.test(m.description))
      .forEach(mapping => {
        lines.push(`  --${mapping.semantic}: var(--${mapping.foundation});`);
      });
  });

  lines.push('}');
  lines.push('');

  return lines.join('\n');
}

/**
 * Generate semantic spacing CSS
 */
function generateSemanticSpacingCSS(): string {
  const spacingMappings = getSemanticMappingsByCategory('spacing');
  
  const lines: string[] = [
    '/**',
    ' * Semantic Spacing Tokens',
    ' * ',
    ' * Universal spacing tokens that map to foundation layer',
    ' * ',
    ' * Do not edit this file directly. It is generated by:',
    ' * npm run generate:semantic',
    ' */',
    '',
    ':root {',
    '  /* ================================== */',
    '  /* Spacing Scale                      */',
    '  /* ================================== */',
    ''
  ];

  // Spacing scale tokens
  spacingMappings
    .filter(m => m.description.includes('spacing'))
    .forEach(mapping => {
      lines.push(`  --${mapping.semantic}: var(--spacing-${mapping.foundation});`);
    });

  lines.push('');
  lines.push('  /* ================================== */');
  lines.push('  /* Component Spacing                  */');
  lines.push('  /* ================================== */');
  lines.push('');

  // Component spacing tokens
  spacingMappings
    .filter(m => m.description.includes('padding') || m.description.includes('gap'))
    .forEach(mapping => {
      lines.push(`  --${mapping.semantic}: var(--spacing-${mapping.foundation});`);
    });

  lines.push('}');
  lines.push('');

  return lines.join('\n');
}

/**
 * Generate semantic typesetting CSS
 */
function generateSemanticTypesettingCSS(): string {
  const typesettingMappings = getSemanticMappingsByCategory('typesetting');
  
  const lines: string[] = [
    '/**',
    ' * Semantic Typesetting Tokens',
    ' * ',
    ' * Universal typesetting tokens that map to foundation layer',
    ' * ',
    ' * Do not edit this file directly. It is generated by:',
    ' * npm run generate:semantic',
    ' */',
    '',
    ':root {',
    '  /* ================================== */',
    '  /* Font Families                      */',
    '  /* ================================== */',
    ''
  ];

  // Font families
  typesettingMappings
    .filter(m => m.description.includes('font family'))
    .forEach(mapping => {
      lines.push(`  --${mapping.semantic}: var(--font-${mapping.foundation});`);
    });

  lines.push('');
  lines.push('  /* ================================== */');
  lines.push('  /* Font Sizes                         */');
  lines.push('  /* ================================== */');
  lines.push('');

  // Font sizes
  typesettingMappings
    .filter(m => m.description.includes('text ('))
    .forEach(mapping => {
      lines.push(`  --${mapping.semantic}: var(--font-size-${mapping.foundation});`);
    });

  lines.push('');
  lines.push('  /* ================================== */');
  lines.push('  /* Font Weights                       */');
  lines.push('  /* ================================== */');
  lines.push('');

  // Font weights
  typesettingMappings
    .filter(m => m.description.includes('font weight'))
    .forEach(mapping => {
      lines.push(`  --${mapping.semantic}: var(--font-weight-${mapping.foundation});`);
    });

  lines.push('');
  lines.push('  /* ================================== */');
  lines.push('  /* Line Heights                       */');
  lines.push('  /* ================================== */');
  lines.push('');

  // Line heights
  typesettingMappings
    .filter(m => m.description.includes('line height'))
    .forEach(mapping => {
      lines.push(`  --${mapping.semantic}: var(--line-height-${mapping.foundation});`);
    });

  lines.push('}');
  lines.push('');

  return lines.join('\n');
}

/**
 * Generate semantic shadow CSS
 */
function generateSemanticShadowCSS(): string {
  const shadowMappings = getSemanticMappingsByCategory('shadow');
  
  const lines: string[] = [
    '/**',
    ' * Semantic Shadow Tokens',
    ' * ',
    ' * Universal shadow tokens that map to foundation layer',
    ' * ',
    ' * Do not edit this file directly. It is generated by:',
    ' * npm run generate:semantic',
    ' */',
    '',
    ':root {',
    '  /* ================================== */',
    '  /* Shadows                            */',
    '  /* ================================== */',
    ''
  ];

  shadowMappings.forEach(mapping => {
    lines.push(`  --${mapping.semantic}: var(--shadow-${mapping.foundation});`);
  });

  lines.push('}');
  lines.push('');

  return lines.join('\n');
}

/**
 * Generate semantic opacity CSS
 */
function generateSemanticOpacityCSS(): string {
  const opacityMappings = getSemanticMappingsByCategory('opacity');
  
  const lines: string[] = [
    '/**',
    ' * Semantic Opacity Tokens',
    ' * ',
    ' * Universal opacity tokens that map to foundation layer',
    ' * ',
    ' * Do not edit this file directly. It is generated by:',
    ' * npm run generate:semantic',
    ' */',
    '',
    ':root {',
    '  /* ================================== */',
    '  /* Opacity                            */',
    '  /* ================================== */',
    ''
  ];

  opacityMappings.forEach(mapping => {
    lines.push(`  --${mapping.semantic}: var(--opacity-${mapping.foundation});`);
  });

  lines.push('}');
  lines.push('');

  return lines.join('\n');
}

/**
 * Generate semantic z-index CSS
 */
function generateSemanticZIndexCSS(): string {
  const zIndexMappings = getSemanticMappingsByCategory('z-index');
  
  const lines: string[] = [
    '/**',
    ' * Semantic Z-Index Tokens',
    ' * ',
    ' * Universal z-index tokens that map to foundation layer',
    ' * ',
    ' * Do not edit this file directly. It is generated by:',
    ' * npm run generate:semantic',
    ' */',
    '',
    ':root {',
    '  /* ================================== */',
    '  /* Z-Index                            */',
    '  /* ================================== */',
    ''
  ];

  zIndexMappings.forEach(mapping => {
    lines.push(`  --${mapping.semantic}: var(--z-index-${mapping.foundation});`);
  });

  lines.push('}');
  lines.push('');

  return lines.join('\n');
}

/**
 * Generate semantic flex CSS
 */
function generateSemanticFlexCSS(): string {
  const flexMappings = getSemanticMappingsByCategory('flex');
  
  const lines: string[] = [
    '/**',
    ' * Semantic Flex Tokens',
    ' * ',
    ' * Universal flex tokens that map to foundation layer',
    ' * ',
    ' * Do not edit this file directly. It is generated by:',
    ' * npm run generate:semantic',
    ' */',
    '',
    ':root {',
    '  /* ================================== */',
    '  /* Flex                               */',
    '  /* ================================== */',
    ''
  ];

  flexMappings.forEach(mapping => {
    lines.push(`  --${mapping.semantic}: var(--flex-${mapping.foundation});`);
  });

  lines.push('}');
  lines.push('');

  return lines.join('\n');
}

/**
 * Generate semantic order CSS
 */
function generateSemanticOrderCSS(): string {
  const orderMappings = getSemanticMappingsByCategory('order');
  
  const lines: string[] = [
    '/**',
    ' * Semantic Order Tokens',
    ' * ',
    ' * Universal order tokens that map to foundation layer',
    ' * ',
    ' * Do not edit this file directly. It is generated by:',
    ' * npm run generate:semantic',
    ' */',
    '',
    ':root {',
    '  /* ================================== */',
    '  /* Order                              */',
    '  /* ================================== */',
    ''
  ];

  orderMappings.forEach(mapping => {
    lines.push(`  --${mapping.semantic}: var(--order-${mapping.foundation});`);
  });

  lines.push('}');
  lines.push('');

  return lines.join('\n');
}

/**
 * Generate all.css convenience import
 */
function generateSemanticAllCSS(): string {
  return [
    '/**',
    ' * Semantic Tokens - All',
    ' * ',
    ' * Convenience import for all semantic tokens',
    ' * ',
    ' * Usage:',
    " *   @import 'svelte-ui/tokens/semantic/all.css';",
    ' * ',
    ' * Note: This requires foundation tokens to be loaded first:',
    " *   @import 'svelte-ui/tokens/foundation/uswds/all.css';",
    " *   @import 'svelte-ui/tokens/semantic/all.css';",
    ' */',
    '',
    '@import \'./color.css\';',
    '@import \'./spacing.css\';',
    '@import \'./typesetting.css\';',
    '@import \'./shadow.css\';',
    '@import \'./opacity.css\';',
    '@import \'./z-index.css\';',
    '@import \'./flex.css\';',
    '@import \'./order.css\';',
    ''
  ].join('\n');
}

/**
 * Main generator function
 */
export function generateSemanticCSS() {
  console.log('=== Semantic Layer CSS Generator ===\n');

  // Create output directory
  mkdirSync(OUTPUT_DIR, { recursive: true });
  console.log(`Output directory: ${OUTPUT_DIR}`);

  // Count tokens by category
  const tokenCounts = {
    color: getSemanticMappingsByCategory('color').length,
    spacing: getSemanticMappingsByCategory('spacing').length,
    typesetting: getSemanticMappingsByCategory('typesetting').length,
    shadow: getSemanticMappingsByCategory('shadow').length,
    opacity: getSemanticMappingsByCategory('opacity').length,
    'z-index': getSemanticMappingsByCategory('z-index').length,
    flex: getSemanticMappingsByCategory('flex').length,
    order: getSemanticMappingsByCategory('order').length
  };

  const totalTokens = Object.values(tokenCounts).reduce((sum, count) => sum + count, 0);

  // Generate CSS files
  console.log('\nGenerating semantic CSS files...');

  const files = [
    { name: 'color.css', content: generateSemanticColorCSS() },
    { name: 'spacing.css', content: generateSemanticSpacingCSS() },
    { name: 'typesetting.css', content: generateSemanticTypesettingCSS() },
    { name: 'shadow.css', content: generateSemanticShadowCSS() },
    { name: 'opacity.css', content: generateSemanticOpacityCSS() },
    { name: 'z-index.css', content: generateSemanticZIndexCSS() },
    { name: 'flex.css', content: generateSemanticFlexCSS() },
    { name: 'order.css', content: generateSemanticOrderCSS() },
    { name: 'all.css', content: generateSemanticAllCSS() }
  ];

  files.forEach(file => {
    const filePath = resolve(OUTPUT_DIR, file.name);
    writeFileSync(filePath, file.content, 'utf-8');
    const category = file.name.replace('.css', '') as keyof typeof tokenCounts;
    const count = tokenCounts[category];
    if (count !== undefined) {
      console.log(`  ✅ ${file.name} (${count} tokens)`);
    } else {
      console.log(`  ✅ ${file.name}`);
    }
  });

  console.log('\n✅ Semantic CSS generation complete!');
  console.log(`\nTotal semantic tokens: ${totalTokens}`);
  console.log('\nToken breakdown:');
  Object.entries(tokenCounts).forEach(([category, count]) => {
    console.log(`  - ${category}: ${count}`);
  });
}

// Run if called directly
if (import.meta.url === `file://${process.argv[1]}`) {
  generateSemanticCSS();
}
