/**
 * Utility Class Generator
 *
 * Generates single-purpose CSS utility classes that reference semantic tokens.
 * Supports responsive variants (5 breakpoints) and state variants (hover, focus, etc).
 *
 * Architecture:
 *   Semantic Tokens → Utility Mappings → Utility CSS (with variants)
 *
 * Usage:
 *   npm run generate:utilities
 *   tsx src/lib/token-generators/generate-utilities.ts
 *
 * @module generate-utilities
 */

import { writeFileSync, mkdirSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';
import { 
  BREAKPOINTS, 
  STATE_VARIANTS, 
  VARIANT_CONFIG,
  getBreakpoints,
  type Breakpoint,
  type StateVariant,
  type UtilityCategory 
} from './utility-config.js';
import type { UtilityMapping } from './types.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const OUTPUT_DIR = resolve(__dirname, '../../tokens/utilities');

/**
 * Escape special characters in CSS class names
 *
 * Examples:
 *   mobile:text-lg  → mobile\:text-lg
 *   w-1/2           → w-1\/2
 *   -mt-2           → \-mt-2
 */
export function escapeClassName(className: string): string {
  return className
    .replace(/:/g, '\\:')   // Escape colons (for prefixes)
    .replace(/\//g, '\\/')  // Escape slashes (for fractions)
    .replace(/\./g, '\\.')  // Escape dots
    .replace(/^-/, '\\-');  // Escape leading dash
}

/**
 * Generate CSS for a base utility class
 */
export function generateBaseUtility(utility: UtilityMapping): string {
  const escapedClass = escapeClassName(utility.className);
  const properties = Array.isArray(utility.properties) 
    ? utility.properties 
    : [utility.properties];
  
  const values = Array.isArray(utility.values)
    ? utility.values
    : Array(properties.length).fill(utility.values);

  const lines: string[] = [];
  
  if (utility.description) {
    lines.push(`  /* ${utility.description} */`);
  }
  
  lines.push(`  .${escapedClass} {`);
  properties.forEach((prop, index) => {
    const important = utility.important ? ' !important' : '';
    lines.push(`    ${prop}: ${values[index]}${important};`);
  });
  lines.push(`  }`);
  lines.push('');
  
  return lines.join('\n');
}

/**
 * Generate CSS for a responsive variant of a utility
 */
export function generateResponsiveVariant(
  utility: UtilityMapping,
  breakpoint: Breakpoint
): string {
  const prefixedClass = `${breakpoint}:${utility.className}`;
  const escapedClass = escapeClassName(prefixedClass);
  
  const properties = Array.isArray(utility.properties) 
    ? utility.properties 
    : [utility.properties];
  
  const values = Array.isArray(utility.values)
    ? utility.values
    : Array(properties.length).fill(utility.values);

  const lines: string[] = [];
  lines.push(`  .${escapedClass} {`);
  properties.forEach((prop, index) => {
    const important = utility.important ? ' !important' : '';
    lines.push(`    ${prop}: ${values[index]}${important};`);
  });
  lines.push(`  }`);
  lines.push('');
  
  return lines.join('\n');
}

/**
 * Generate CSS for a state variant of a utility
 */
export function generateStateVariant(
  utility: UtilityMapping,
  state: StateVariant
): string {
  const prefixedClass = `${state}:${utility.className}`;
  const escapedClass = escapeClassName(prefixedClass);
  const pseudoClass = STATE_VARIANTS[state];
  
  const properties = Array.isArray(utility.properties) 
    ? utility.properties 
    : [utility.properties];
  
  const values = Array.isArray(utility.values)
    ? utility.values
    : Array(properties.length).fill(utility.values);

  const lines: string[] = [];
  lines.push(`  .${escapedClass}${pseudoClass} {`);
  properties.forEach((prop, index) => {
    const important = utility.important ? ' !important' : '';
    lines.push(`    ${prop}: ${values[index]}${important};`);
  });
  lines.push(`  }`);
  lines.push('');
  
  return lines.join('\n');
}

/**
 * Generate complete CSS file for a utility category
 */
export function generateCategoryCSS(
  category: UtilityCategory,
  utilities: UtilityMapping[]
): string {
  const categoryTitle = category.charAt(0).toUpperCase() + category.slice(1);
  
  const lines: string[] = [
    '/**',
    ` * ${categoryTitle} Utility Classes`,
    ' *',
    ' * Single-purpose utility classes that reference semantic tokens.',
    ' *',
    ' * Generated by: src/lib/token-generators/generate-utilities.ts',
    ` * Source mappings: src/lib/token-generators/utility-mappings/${category}-utilities.ts`,
    ' *',
    ' * To customize: Edit the source mapping file and run \'npm run generate:utilities\'',
    ' */',
    ''
  ];
  
  // Generate base utilities
  lines.push('/* Base Utilities */');
  lines.push('');
  utilities.forEach(utility => {
    lines.push(generateBaseUtility(utility));
  });
  
  // Generate responsive variants if enabled for this category
  const hasResponsive = VARIANT_CONFIG.responsive[category];
  if (hasResponsive) {
    const breakpoints = getBreakpoints();
    breakpoints.forEach(breakpoint => {
      const minWidth = BREAKPOINTS[breakpoint];
      lines.push(`/* Responsive: ${breakpoint} (min-width: ${minWidth}) */`);
      lines.push(`@media (min-width: ${minWidth}) {`);
      lines.push('');
      
      utilities.forEach(utility => {
        // Allow per-utility override
        if (utility.responsive !== false) {
          lines.push(generateResponsiveVariant(utility, breakpoint));
        }
      });
      
      lines.push('}');
      lines.push('');
    });
  }
  
  // Generate state variants if defined for this category
  const stateList = VARIANT_CONFIG.states[category];
  if (stateList && stateList.length > 0) {
    lines.push('/* State Variants */');
    lines.push('');
    
    utilities.forEach(utility => {
      // Use utility-specific states if defined, otherwise use category defaults
      const utilityStates = utility.states || stateList;
      utilityStates.forEach(state => {
        lines.push(generateStateVariant(utility, state as StateVariant));
      });
    });
  }
  
  return lines.join('\n');
}

/**
 * Generate all.css convenience import file
 */
export function generateAllCSS(categories: UtilityCategory[]): string {
  const lines: string[] = [
    '/**',
    ' * All Utility Classes',
    ' *',
    ' * Convenience import for all utility categories.',
    ' *',
    ' * Import this for all utilities, or import individual category files',
    ' * for selective loading.',
    ' *',
    ' * Usage:',
    " *   @import 'svelte-ui/tokens/utilities/all.css';",
    ' *',
    ' * Or selective:',
    " *   @import 'svelte-ui/tokens/utilities/color.css';",
    " *   @import 'svelte-ui/tokens/utilities/spacing.css';",
    ' *',
    ' * Generated by: src/lib/token-generators/generate-utilities.ts',
    ' */',
    ''
  ];
  
  categories.forEach(category => {
    lines.push(`@import './${category}.css';`);
  });
  
  lines.push('');
  
  return lines.join('\n');
}

/**
 * Main generator function
 */
export async function generateUtilities() {
  console.log('=== Utility Class Generator ===\n');
  
  // Import utility mappings
  // For now, we'll use an empty placeholder since we haven't created the mappings yet
  const allUtilityMappings: UtilityMapping[] = [];
  
  try {
    const { allUtilityMappings: imported } = await import('./utility-mappings/index.js');
    allUtilityMappings.push(...imported);
  } catch (error) {
    console.log('Note: No utility mappings found yet. Skipping generation.');
    console.log('Create utility-mappings/index.ts to define utilities.\n');
    return;
  }
  
  // Group utilities by category
  const utilitiesByCategory = new Map<UtilityCategory, UtilityMapping[]>();
  allUtilityMappings.forEach(utility => {
    if (!utilitiesByCategory.has(utility.category)) {
      utilitiesByCategory.set(utility.category, []);
    }
    utilitiesByCategory.get(utility.category)!.push(utility);
  });
  
  // Create output directory
  mkdirSync(OUTPUT_DIR, { recursive: true });
  console.log(`Output directory: ${OUTPUT_DIR}`);
  
  console.log('\nGenerating utility CSS files...');
  
  // Generate category files
  const categoryFiles: { name: string; count: number }[] = [];
  utilitiesByCategory.forEach((utilities, category) => {
    const filename = `${category}.css`;
    const content = generateCategoryCSS(category, utilities);
    const filepath = resolve(OUTPUT_DIR, filename);
    writeFileSync(filepath, content, 'utf-8');
    
    // Count total utilities (base + responsive + states)
    let totalCount = utilities.length; // Base utilities
    
    // Add responsive variant count
    if (VARIANT_CONFIG.responsive[category]) {
      const responsiveUtilities = utilities.filter(u => u.responsive !== false);
      totalCount += responsiveUtilities.length * getBreakpoints().length;
    }
    
    // Add state variant count
    const stateList = VARIANT_CONFIG.states[category];
    if (stateList && stateList.length > 0) {
      utilities.forEach(utility => {
        const utilityStates = utility.states || stateList;
        totalCount += utilityStates.length;
      });
    }
    
    categoryFiles.push({ name: filename, count: totalCount });
    console.log(`  ✅ ${filename} (${totalCount} utilities)`);
  });
  
  // Generate all.css
  const categories = Array.from(utilitiesByCategory.keys());
  const allCSS = generateAllCSS(categories);
  writeFileSync(resolve(OUTPUT_DIR, 'all.css'), allCSS, 'utf-8');
  console.log('  ✅ all.css');
  
  // Summary
  const totalUtilities = categoryFiles.reduce((sum, file) => sum + file.count, 0);
  console.log(`\n✅ Utility generation complete!`);
  console.log(`\nTotal utilities: ${totalUtilities}`);
  console.log('\nUtility breakdown:');
  categoryFiles.forEach(({ name, count }) => {
    console.log(`  - ${name}: ${count}`);
  });
}

// Run if called directly
if (import.meta.url === `file://${process.argv[1]}`) {
  generateUtilities().catch(error => {
    console.error('\n❌ Error generating utilities:', error.message);
    process.exit(1);
  });
}
